### ISSUE TITLE
Include benchmark results in the repo

### ISSUE THREAD

**Issue by mcollina** [WebReflection/raytrace#1]

**Comment by WebReflection** [comment]
## TS - WebKit

![Screenshot from 2023-09-04 11-23-16](https://github.com/WebReflection/raytrace/assets/85749/2894f6cb-6de3-486b-a8ee-13d3c7deacde)

## JS - WebKit

![Screenshot from 2023-09-04 11-23-16](https://github.com/WebReflection/raytrace/assets/85749/5a8f50a6-c3be-4c26-9a52-aa41e95dcac4)

**Comment by WebReflection** [comment]
I can screenshot various browsers (my driver here) and you'll see JS 1.5x up to 3x faster in general on both Desktop or Mobile.
